name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn clean install

      - name: Generate JUnit Report
        run: mvn surefire-report:report

      - name: Upload JUnit Report
        uses: actions/upload-artifact@v2
        with:
          name: junit-reports
          path: target/surefire-reports/*.xml
